language: node_js

node_js:
  - "iojs-1"
  - "0.12"
  - "0.11"
  - "0.10"

before_script:
  - "./start-local-hbase.sh"

script: "make test-travis"
after_script: "npm install coveralls@2 && cat ./coverage/lcov.info | coveralls"
